name: Helm deploy with support for Helm Secrets
description: Helm deploy action with support for Helm Secrets
author: Ivido
inputs:
  # Many of these are taken from deliverybot/helm
  release:
    description: Helm release name. (required)
    required: true
  namespace:
    description: Kubernetes namespace name. (required)
    required: true
  chart:
    description: Helm chart path. (required)
    required: true
  chart-version:
    description: Helm chart version.
    required: false
  repository:
    description: Helm repository to get the chart from.
    required: false
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
    required: false
  value-files:
    description:
      Additional value files to apply to the helm chart. Expects JSON encoded
      array or a string.
    required: false
  secrets-files:
    description: Helm Secrets files to apply to the helm chart as values.
    required: false
  task:
    description: Task name. If the task is "remove" it will remove the configured helm release.
    required: false
  dry-run:
    description: Helm dry-run option
    required: false
  atomic:
    description:
      If true, upgrade process rolls back changes made in case of failed upgrade.
      Defaults to true.
    required: false
  timeout:
    description: Helm upgrade timeout.
    required: false
  image:
    description: Image to deploy. Overrides the values specified by imageFields.
    required: false
  image-fields:
    description: Fields to insert the image name in. Expects JSON encoded array or a string. Defaults to "image.name".
    required: false
  tag:
    description: Image tag to deploy, usually commit sha or Git tag. Overrides the values specified by tagFields.
    required: false
  tag-fields:
    description: Fields to insert the image tags in. Expects JSON encoded array or a string. Defaults to "image.tag".
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: anchor
  color: blue
